description: "Riverview Hotel"
publisher: "Riverview Hotel"
keywords: "Hotel, Pub, Murwillumbah, beer, wine, spirits, games, lunch, dinner, stylish, fun, friendly"
title: "Riverview Hotel"

biz_name: "Riverview Hotel"
biz_slog: ""

biz_addr_1: "267 Tweed Valley Way"
biz_addr_2:
biz_addr_city: "Murwillumbah"
biz_addr_state: "NSW"
biz_addr_code: "2484"

biz_map: <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3512.000654829023!2d153.40130261567384!3d-28.328581882538717!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6b90f00697a90e3d%3A0xa3df14c8cd6dbd60!2sRiverview+Hotel!5e0!3m2!1sen!2sau!4v1474697726829" width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
biz_map_url: "https://www.google.com/maps/place/Riverview+Hotel/@-28.331113,153.404961,15z/data=!4m5!3m4!1s0x0:0xa3df14c8cd6dbd60!8m2!3d-28.3285819!4d153.4034913?hl=en-US"

biz_post_box:
biz_post_city:
biz_post_state:
biz_post_code:

biz_phone: "02 6672 1006"
biz_phone_bus: "0488 533 780"
biz_phone_bistro: "02 6672 4772"
biz_fax:
biz_email: "staff@rvhm.com.au"

biz_abn: "72 610 964 022"

pop-img:

url: "//www.rvhm.com.au"
cdn: "https://cdn.rvhm.com.au"

permalink: pretty

paginate: 5
paginate_path: "/blog/:num/"

gems:
  - jekyll-redirect-from
