description: "Riverview Hotel"
publisher: "Riverview Hotel"
keywords: "Hotel, Pub, Murwillumbah, beer, wine, spirits, games, lunch, dinner, stylish, fun, friendly"
title: "Riverview Hotel"

biz_name: "Riverview Hotel"
biz_slog: "Brew with a view"

biz_addr_1: "267 Tweed Valley Way"
biz_addr_2:
biz_addr_city: "Murwillumbah"
biz_addr_state: "NSW"
biz_addr_code: "2484"

biz_post_box:
biz_post_city:
biz_post_state:
biz_post_code:

biz_phone: "02 6672 1006"
biz_fax:
biz_email: "staff@rvhm.com.au"

biz_abn: "72 610 964 022"

pop-img:

url: "//www.rvhm.com.au"
cdn: "//cdn.rvhm.com.au"

permalink: pretty

paginate: 5
paginate_path: "/blog/:num/"

gems:
  - jekyll-redirect-from
